# Generated by Django 5.1.6 on 2025-02-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
