# Generated by Django 5.1.6 on 2025-02-21 13:37

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16, unique=True),
        ),
    ]
