# Generated by Django 5.1.6 on 2025-03-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
