version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - "5434:5432"
    container_name: eLearning_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  

  redis:
    image: redis:7
    restart: always
    container_name: eLearning_redis

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: eLearning_backend
    restart: always
    volumes:
      - ./Backend:/app
    ports:
      - "8002:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: eLearning_celery
    restart: always
    command: celery -A core worker --loglevel=info
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: eLearning_frontend
    restart: always
    volumes:
      - ./Frontend:/frontend
    ports:
      - "3002:3000"

volumes:
  postgres_data: