# Generated by Django 5.1.6 on 2025-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
