# Generated by Django 5.1.6 on 2025-03-03 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursematerial_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=255, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
